# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20171022_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.IntegerField(unique=True),
        ),
    ]
